### ISSUE TITLE
Fix MCD/MLD/DB

### ISSUE THREAD

**Issue by eli-ott** [eli-ott/foto_cubes#53]
Ajouter une colonne dans la base pour savoir si l'utilisateur est admin ou non

**Comment by eli-ott** [comment]
MCD fixed :

![Image](https://github.com/eli-ott/foto_cubes/assets/74316463/c00f0693-6f2c-4a03-9686-1f3c29bbc1ef)


MLD fixed :

mot_de_passe(#id_mot_de_passe, hash, nb_essais, date_reinitialisation);

utilisateur (#id_user, #id_mot_de_passe, pseudo, nom, prenom, email, age, type_photo_pref, date_creation, warn, id_admin)

photo (#id_photo, #id_user, titre, tag, date_prise_vue, source, date_publication, warn)

envoyer (#id_envoyeur, #id_receveur, message)

**Comment by eli-ott** [comment]
See PR from issue #74

**Comment by eli-ott** [comment]
Refix

MCD
![Image](https://github.com/eli-ott/foto_cubes/assets/74316463/10ca3dd1-bcd6-4a2a-9cf4-f21514fa99af)

MLD

mot_de_passe(#id_mot_de_passe, #id_user hash, nb_essais, date_reinitialisation);

utilisateur (#id_user, #id_mot_de_passe, pseudo, nom, prenom, email, age, type_photo_pref, date_creation, warn, id_admin)

photo (#id_photo, #id_user, titre, tag, date_prise_vue, source, date_publication, warn)

envoyer (#id_envoyeur, #id_receveur, message)

**Comment by B4pt01** [comment]
![Image](https://github.com/eli-ott/foto_cubes/assets/147141384/284d8e0f-d3c2-4245-ad06-72f805729c57)
